### ISSUE TITLE
Create separate page to show Inter IIT Tech Meet achievements for all years.

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/sntc#30]

**Comment by vsvipul** [comment]
@kpbot claim

**Comment by vsvipul** [comment]
@kpbot abandon

**Comment by vsvipul** [comment]
We have received the following medals this time at Inter IIT Tech Meet 9.0, conducted by IIT Guwahati.
1) Gold in QuantInsti Algorithmic Trading 🥇
(Aryan Goyal, Vineet Ahuja, Dheeraj Yadav, Sanskar Gupta, Anshika Bajpai)
2) Silver in SaptangLabs Security Hackathon 🥈
(Milind Topno, Yash Bansod, Pranshu Kharkwal, Dhruv Pindawala, Divyasheel Kumar)
3) Bronze in Bridge i2i Automated Headline and Sentiment Generator 🥉
(Abhijeet Manhas, Khyati Agarwal, Piyush Goyal, Prakhar Uniyal, Naman Tayal, Prajjwal Jha, Manan Shah, Rishabh Garg, Paras Jain, Yash Verma)
Also much thanks to people who participated in Engineer's Conclave 🎖️ :
Prajwal Sood, Aakash Maurya, Khushi, Manish, Arjun, Vivek Mittal

Also thanks to our Contingent Leader Arjun Sahdev for managing the teams and submissions so well.

Add the above data for Tech Meet '20, to the page.

**Comment by metavinayak** [comment]
Working on it.

Overview:
Renaming the page TM_2019.html and adding the IIT Tech Meet 2020 details along with IIT Tech Meet 2019(on the current TM_2019.html).
Renaming and updating the links.

**Comment by metavinayak** [comment]
PR sent.Pls verify.
