### ISSUE TITLE
Make navwheel smaller for mobile devices

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/sntc#8]
Reduce the size of the navwheel in home tab for mobile devices.

**Comment by vsvipul** [comment]
@kpbot claim

**Comment by vsvipul** [comment]
@kpbot claim

**Comment by vsvipul** [comment]
@kpbot claim

**Comment by vsvipul** [comment]
@kpbot claim

**Comment by vsvipul** [comment]
@kpbot claim

**Comment by vsvipul** [comment]
@kpbot abandon

**Comment by Signior-X** [comment]
@kpbot claim

**Comment by Swapnilr1** [comment]
How to reproduce this issue? @vsvipul 
The website seems to work fine when I tested with Firefox mobile and Chrome mobile versions.
